import os
import shutil
from datetime import datetime

print("="*80)
print("ORGANIZING OUTPUT FILES")
print("="*80)

# Create output folder with timestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_folder = f"digital_divide_outputs_{timestamp}"

# Create the folder
os.makedirs(output_folder, exist_ok=True)
print(f"\n✅ Created folder: {output_folder}")

# Define output files to move
output_files = {
    'CSV Files': [
        'merged_aadhaar_data.csv',
        'processed_aadhaar_data.csv',
        'district_clusters.csv',
        'final_summary_statistics.csv'
    ],
    'Visualizations': [
        'viz1_digital_deserts.png',
        'viz2_state_comparison.png',
        'viz3_time_series.png',
        'viz4_risk_matrix.png'
    ],
    'ML Model Outputs': [
        'model1_clustering.png',
        'model2_confusion_matrix.png',
        'model2_feature_importance.png'
    ]
}

# Move files by category
print("\n" + "="*80)
print("MOVING FILES")
print("="*80)

total_moved = 0
total_missing = 0

for category, files in output_files.items():
    print(f"\n{category}:")
    for file in files:
        if os.path.exists(file):
            destination = os.path.join(output_folder, file)
            shutil.copy2(file, destination)
            print(f"  ✅ {file}")
            total_moved += 1
        else:
            print(f"  ❌ {file} (not found)")
            total_missing += 1

# Create a README file in the output folder
readme_content = f"""# Digital Divide Predictor - Output Files

Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Contents

### CSV Files
- **merged_aadhaar_data.csv**: Combined dataset from enrolment, demographic, and biometric updates
- **processed_aadhaar_data.csv**: Cleaned and processed data with calculated metrics
- **district_clusters.csv**: District-level clustering results with DLI and IGS scores
- **final_summary_statistics.csv**: Summary statistics from the final report

### Visualizations
- **viz1_digital_deserts.png**: Geographic distribution of digital divide
- **viz2_state_comparison.png**: State-wise comparison of digital literacy
- **viz3_time_series.png**: Temporal trends in updates
- **viz4_risk_matrix.png**: Risk assessment matrix for districts

### ML Model Outputs
- **model1_clustering.png**: K-Means clustering visualization
- **model2_confusion_matrix.png**: Random Forest classifier performance
- **model2_feature_importance.png**: Feature importance analysis

## Key Metrics
- Total Records: 1,081,603
- Unique Districts: 1,083
- States/UTs Covered: 51
- Average Digital Literacy Index: 0.186

## Usage
These files are ready for:
- Presentation and reporting
- Further analysis
- Hackathon submission
- Policy recommendations

---
Generated by Digital Divide Predictor Pipeline
"""

readme_path = os.path.join(output_folder, 'README.md')
with open(readme_path, 'w', encoding='utf-8') as f:
    f.write(readme_content)
print(f"\n✅ Created README.md in output folder")

# Summary
print("\n" + "="*80)
print("SUMMARY")
print("="*80)
print(f"\nTotal files moved: {total_moved}")
print(f"Missing files: {total_missing}")
print(f"\nAll outputs saved to: {output_folder}/")
print("\n✅ Organization complete!")
print("="*80)
